### ISSUE TITLE
Wallet 0.13.1

### ISSUE THREAD

**Issue by pfreak2000** [kr1z1s/p2pool-aby#1]
can i run the pool with 0.13.1 ?
i use windows 10 and the last wallet for windows is 0.13.1

**Comment by kr1z1s** [comment]
What exactly is your problem?

**Comment by pfreak2000** [comment]
i use the last windows wallet from artybyte 0.13.1
But the pool need 0.13.2 so i got this error

2017-12-19 17:12:49.259000 p2pool (version 19b0aab)
2017-12-19 17:12:49.275000
2017-12-19 17:12:49.275000 Testing bitcoind RPC connection to 'http://127.0.0.1:8607/' with username ''...
2017-12-19 17:12:49.290000 Coin daemon too old! Upgrade!
2017-12-19 17:12:50.306000 Coin daemon too old! Upgrade!

**Comment by kr1z1s** [comment]
To https://github.com/kr1z1s/p2pool-aby/blob/master/p2pool/networks/artbyte.py

In SOFTFORKS_REQUIRED = set(['segsignal', 'csv', 'segwit'])

Change

SOFTFORKS_REQUIRED = set(['bip65', 'csv', 'segwit'])

**Comment by pfreak2000** [comment]
ok now got this failur

Error getting work from bitcoind:
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1442, in gotResult
    _inlineCallbacks(r, g, deferred)
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "C:\Python27\lib\site-packages\twisted\python\failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
--- <exception caught here> ---
  File "C:\Users\p2pool\Desktop\P2Pool Daten\p2pool-neoscrypt\p2pool\util\deferral.py", line 41, in f
    result = yield func(*args, **kwargs)
  File "C:\Python27\lib\site-packages\twisted\internet\defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "C:\Users\p2pool\Desktop\P2Pool Daten\p2pool-neoscrypt\p2pool\bitcoin\helper.py", line 61, in getwork
    transactions=map(bitcoin_data.tx_type.unpack, packed_transactions),
  File "C:\Users\p2pool\Desktop\P2Pool Daten\p2pool-neoscrypt\p2pool\util\pack.py", line 63, in unpack
    obj = self._unpack(data, ignore_trailing)
  File "C:\Users\p2pool\Desktop\P2Pool Daten\p2pool-neoscrypt\p2pool\util\pack.py", line 42, in _unpack
    obj, (data2, pos) = self.read((data, 0))
  File "C:\Users\p2pool\Desktop\P2Pool Daten\p2pool-neoscrypt\p2pool\util\pack.py", line 295, in read
    item[key], file = type_.read(file)
  File "C:\Users\p2pool\Desktop\P2Pool Daten\p2pool-neoscrypt\p2pool\util\pack.py", line 171, in read
    res[i], file = self.type.read(file)
  File "C:\Users\p2pool\Desktop\P2Pool Daten\p2pool-neoscrypt\p2pool\util\pack.py", line 295, in read
    item[key], file = type_.read(file)
  File "C:\Users\p2pool\Desktop\P2Pool Daten\p2pool-neoscrypt\p2pool\util\pack.py", line 132, in read
    return read(file, length)
  File "C:\Users\p2pool\Desktop\P2Pool Daten\p2pool-neoscrypt\p2pool\util\pack.py", line 16, in read
    raise EarlyEnd()
p2pool.util.pack.EarlyEnd:

**Comment by kr1z1s** [comment]
Hey!!!
p2pool-neoscrypt

This is not my pool

**Comment by pfreak2000** [comment]
haha sorry wrong icon. your pool run *thumps up*

**Comment by pfreak2000** [comment]
pool run but i got this in log

2Error while processing Event callbacks:
Traceback (most recent call last):
  File "C:\Users\p2pool\Desktop\P2Pool Daten\p2pool-aby\p2pool\data.py", line 556, in think
    if not self.attempt_verify(share):
  File "C:\Users\p2pool\Desktop\P2Pool Daten\p2pool-aby\p2pool\data.py", line 505, in attempt_verify
    self.verified.add(share)
  File "C:\Users\p2pool\Desktop\P2Pool Daten\p2pool-aby\p2pool\util\forest.py", line 356, in add
    Tracker.add(self, item)
  File "C:\Users\p2pool\Desktop\P2Pool Daten\p2pool-aby\p2pool\util\forest.py", line 277, in add
    self.added.happened(item)
--- <exception caught here> ---
  File "C:\Users\p2pool\Desktop\P2Pool Daten\p2pool-aby\p2pool\util\variable.py", line 42, in happened
    func(*event)
  File "C:\Users\p2pool\Desktop\P2Pool Daten\p2pool-aby\p2pool\node.py", line 274, in _
    print >>sys.stderr, 'GOT INCOMPLETE BLOCK FROM PEER! %s bitcoin: %s%064x' % (p2pool_data.format_hash(share.hash), self.net.PARENT.BLOCK_EXPLORER_URL_PREFIX, share.header_hash)
  File "C:\Users\p2pool\Desktop\P2Pool Daten\p2pool-aby\p2pool\util\logging.py", line 81, in write
    self.inner_file.write(data)
  File "C:\Users\p2pool\Desktop\P2Pool Daten\p2pool-aby\p2pool\util\logging.py", line 99, in write
    self.inner_file.write(self.prefix + line + '\n')
  File "C:\Users\p2pool\Desktop\P2Pool Daten\p2pool-aby\p2pool\util\logging.py", line 69, in write
    self.inner_file.write('%s %s\n' % (datetime.datetime.now(), line))
  File "C:\Users\p2pool\Desktop\P2Pool Daten\p2pool-aby\p2pool\util\logging.py", line 55, in write
    output.write(data)
  File "C:\Users\p2pool\Desktop\P2Pool Daten\p2pool-aby\p2pool\util\logging.py", line 18, in write
    self.inner_file.write(data)
exceptions.IOError: [Errno 0] Error

**Comment by kr1z1s** [comment]
This is windows logging error

I don't know how to help you

**Comment by kr1z1s** [comment]
P2pool cannot write LOG to disk

Maybe not enough rights.
